services:

  ecommerce-frontend:
    volumes:
      - ./ecommerce-frontend/src:/app/src
      - ./ecommerce-frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
      - REACT_APP_ENV=development
    ports:
      - "3000:80"
    command: ["npm", "start"]

  # ecommerce-backend:
  #   volumes:
  #     - ./ecommerce-backend/src:/app/src
  #     - ./ecommerce-backend/package.json:/app/package.json
  #     - ./ecommerce-backend/.env:/app/.env
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=4000
  #   ports:
  #     - "4000:4000"
  #   command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge